services:
  postgres:
    image: postgres:17
    container_name: findthebox-postgres
    environment:
      POSTGRES_DB: findthebox
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_v2_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: findthebox-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_v2_data:/data

volumes:
  postgres_v2_data:
  redis_v2_data:
